### PR TITLE
Add a kuberentes secret for Vault token in vault helm installation.

### PR DESCRIPTION
**Pull request by revit13**
Signed-off-by: Revital Sur <eres@il.ibm.com>
Co-authored-by: Roee Shlomo <roee88@gmail.com>

### CODE REVIEW

**Review by roee88 — APPROVED** [review]

**Comment by roee88** [comment]
Thanks. Please open an issue to improve this as nothing should login as root.

**Comment by revit13** [comment]
@roee88 I opened an issue. Maybe we should consider installing Vault in non dev mode? it seems that we assume we need the token in k8s secret which missed the point of using dev mode where the token is known...

**Comment by roee88** [comment]
I don't mind that the value is root and is known when you install it in dev mode or otherwise, it's not our problem and that's not what I meant. 

What I meant is that this secret you added here is actually not for vault but rather for the manager to login to vault. A proper method to allow the manager to login to vault should be added instead, not relying on such a secret that always has root in it. Be it a secret dedicated to the manager that the user configures (as part of m4d helm install) or using Kubernetes login.

**Comment by revit13** [comment]
@roee88 OK thanks. I'll change the issue to reflect that.

**Pull request merged**
