### PR TITLE
gui updates

### PR DESCRIPTION
**Pull request by shlomitk1**
Signed-off-by: SHLOMITK@il.ibm.com <shlomitk@il.ibm.com>

This PR includes:
- adding a new field for cluster name
- adding a new column for data assets (Destination catalog). If specified, the copy will be made and a new asset will be registered.
- displaying cataloged assets (if relevant) when clicking on status icon

### CODE REVIEW

**Review by simanadler — COMMENTED** [review]
Please add an ingest example to the README, and please add an ingest test case in the Gui server tests

**Review by simanadler — COMMENTED** [review]
Please add an ingest example to the README, and please add an ingest test case in the Gui server tests

**Comment by shlomitk1** [comment]
> 
> 
> Please add an ingest example to the README, and please add an ingest test case in the Gui server tests

Added. In Gui server tests I've replaced a duplicate test case by the ingest test case.

**Review by simanadler — APPROVED** [review]

**Review by simanadler — COMMENTED** [review]
Approved

**Pull request merged**
